<?xml version="1.0"?>
<package format="3">
  <name>recon_drone</name>
  <version>0.0.1</version>
  <description>Recon drone based on sjtu_drone with Velodyne VLP-16 LiDAR and Camera-LiDAR fusion</description>
  <maintainer email="you@email.com">you</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>robot_state_publisher</depend>
  <depend>gazebo_ros</depend>
  <depend>xacro</depend>
  <depend>sjtu_drone_description</depend>
  <depend>sjtu_drone_bringup</depend>
  <depend>topic_tools</depend>
  <depend>rtabmap_slam</depend>
  <depend>rtabmap_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>